name: Build and Test Java Spring Boot Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean verify

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: SpringBoot Artifacts
          path: target/
